"""Pydantic schemas shared across all RAG pipeline modules.

These schemas define the contracts between Rewriter, Searcher, Evaluator,
Generator and the Orchestrator, as well as the debug trace structure.
"""

from __future__ import annotations

import time
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ------------------------------------------------------------------
# Filter / Sort schemas (Rewriter -> Searcher)
# ------------------------------------------------------------------

class FilterOperator(str, Enum):
    EQ = "eq"
    NEQ = "neq"
    GT = "gt"
    LT = "lt"
    GTE = "gte"
    LTE = "lte"
    IN = "in"
    RANGE = "range"


class SortOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class SearchFilter(BaseModel):
    """A single filter condition generated by the Rewriter."""
    field: str = Field(..., description="Payload field name (e.g. 'status', 'metadata.category')")
    operator: FilterOperator = Field(FilterOperator.EQ)
    value: Any = Field(..., description="Filter value (scalar, list for IN, or dict for RANGE)")


class SearchSort(BaseModel):
    """Sort directive generated by the Rewriter."""
    field: str = Field(..., description="Field to sort on")
    order: SortOrder = Field(SortOrder.DESC)


# ------------------------------------------------------------------
# Rewriter output
# ------------------------------------------------------------------

class RewrittenQuery(BaseModel):
    """A single rewritten query produced by the Rewriter module."""
    text: str = Field(..., max_length=1000, description="Rewritten query text")
    filters: List[SearchFilter] = Field(default_factory=list)
    sorts: List[SearchSort] = Field(default_factory=list)
    facet_type: str = Field("", description="Facet label (e.g. 'temporal', 'authority', 'general')")


# ------------------------------------------------------------------
# Evaluator output
# ------------------------------------------------------------------

class EvaluatedDocument(BaseModel):
    """A document scored by the Evaluator (cross-encoder)."""
    document: Dict[str, Any] = Field(..., description="Original document dict from Searcher")
    relevance_score: float = Field(..., ge=0, le=100, description="Cross-encoder score (0-100)")
    query_text: str = Field("", description="Query the document was evaluated against")


# ------------------------------------------------------------------
# Searcher output
# ------------------------------------------------------------------

class SearchResults(BaseModel):
    """Aggregated search results across all rewritten queries."""
    documents: List[Dict[str, Any]] = Field(default_factory=list)
    results_per_query: Dict[str, int] = Field(
        default_factory=dict,
        description="Map of query text -> number of results returned",
    )
    total_before_dedup: int = 0
    total_after_dedup: int = 0


# ------------------------------------------------------------------
# Pipeline debug trace
# ------------------------------------------------------------------

class StageTimings(BaseModel):
    """Millisecond timings for each pipeline stage."""
    rewriter_ms: int = 0
    searcher_ms: int = 0
    evaluator_ms: int = 0
    generator_ms: int = 0
    total_ms: int = 0


class PipelineTrace(BaseModel):
    """Complete debug trace of a single RAG pipeline execution.

    Returned to the caller when ``debug=True``.  Designed to be
    JSON-serialisable so the web UI can render it directly.
    """
    original_query: str = ""
    rewritten_queries: List[RewrittenQuery] = Field(default_factory=list)

    search_results_per_query: Dict[str, int] = Field(default_factory=dict)
    total_documents_found: int = 0
    documents_after_dedup: int = 0

    evaluation_scores: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="[{regulation_id, score, accepted}]",
    )
    documents_accepted: int = 0
    documents_discarded: int = 0
    evaluation_threshold: float = 0

    generator_model: str = ""
    generator_grounded_only: bool = True
    generator_context_length: int = 0

    timings: StageTimings = Field(default_factory=StageTimings)
    errors: List[str] = Field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()
