"""Pydantic schemas shared across all RAG pipeline modules.

These schemas define the contracts between Rewriter, Searcher, Evaluator,
Generator and the Orchestrator, as well as the debug trace structure.

The ``FilterRegistry`` lazily loads distinct ``doc_type`` / ``authority``
values from the SQLite store so that filter prompts and validation stay
in sync with the actual data — no manual list maintenance required.
"""

from __future__ import annotations

import sqlite3
import threading
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Set

from loguru import logger
from pydantic import BaseModel, Field


# ------------------------------------------------------------------
# Filter / Sort schemas (Rewriter -> Searcher)
# ------------------------------------------------------------------

class FilterOperator(str, Enum):
    EQ = "eq"
    NEQ = "neq"
    GT = "gt"
    LT = "lt"
    GTE = "gte"
    LTE = "lte"
    IN = "in"
    RANGE = "range"


class SortOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class SearchFilter(BaseModel):
    """A single filter condition generated by the Rewriter."""
    field: str = Field(..., description="Payload field name (e.g. 'metadata.type', 'metadata.authority')")
    operator: FilterOperator = Field(FilterOperator.EQ)
    value: Any = Field(..., description="Filter value (scalar, list for IN, or dict for RANGE)")


class SearchSort(BaseModel):
    """Sort directive generated by the Rewriter."""
    field: str = Field(..., description="Field to sort on (e.g. 'effective_date')")
    order: SortOrder = Field(SortOrder.DESC)


# ------------------------------------------------------------------
# Domain-specific filter metadata
# ------------------------------------------------------------------

VALID_FACET_TYPES = ["general", "temporal", "authority", "document_type"]

ALLOWED_FILTER_FIELDS = frozenset({"metadata.type", "metadata.authority", "effective_date"})


class FilterRegistry:
    """Lazy-loaded registry of valid filter values.

    On first access it queries ``SELECT DISTINCT doc_type, authority``
    from the SQLite store, ordered by frequency, and caches the result.
    Only the **top N** values are exposed for prompt injection and
    validation — rare values are left to semantic search.

    If the database is unavailable (e.g. unit tests) a static seed list
    is used instead.
    """

    _STATIC_TYPES: List[str] = [
        "ICA", "PCA", "RICA", "MCA", "DCA", "NSCA", "TCA", "FCA",
        "BCA", "BMA", "IMA", "ROCA", "RCA", "NPA",
        "RBAC",  # Regulamentos Brasileiros da Aviação Civil (ANAC)
    ]

    _STATIC_AUTHORITIES: List[str] = [
        "GABAER", "DECEA", "EMAER", "DEPENS", "COMGAP",
        "DCTA", "DIRSA", "CENIPA", "DIRINFRA", "DIRAD",
        "ANAC",  # Agência Nacional de Aviação Civil
    ]

    MAX_PROMPT_TYPES = 14
    MAX_PROMPT_AUTHORITIES = 10

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._loaded = False
        self._top_types: List[str] = []
        self._top_authorities: List[str] = []

    # -- lazy loading ---------------------------------------------------

    def _load(self) -> None:
        if self._loaded:
            return
        with self._lock:
            if self._loaded:
                return
            try:
                from config import config
                db_path = Path(config.STORE_DB_PATH)
                if db_path.exists():
                    self._load_from_db(db_path)
                else:
                    logger.warning(
                        f"FilterRegistry: DB not found at {db_path}, "
                        "using static fallback"
                    )
                    self._use_static()
            except Exception as exc:
                logger.warning(
                    f"FilterRegistry: DB load failed ({exc}), "
                    "using static fallback"
                )
                self._use_static()
            self._loaded = True

    def _load_from_db(self, db_path: Path) -> None:
        conn = sqlite3.connect(str(db_path), timeout=5)
        try:
            rows = conn.execute(
                "SELECT doc_type FROM documents "
                "WHERE doc_type IS NOT NULL "
                "GROUP BY doc_type ORDER BY COUNT(*) DESC "
                f"LIMIT {self.MAX_PROMPT_TYPES}"
            ).fetchall()
            self._top_types = [r[0] for r in rows]

            rows = conn.execute(
                "SELECT authority FROM documents "
                "WHERE authority IS NOT NULL "
                "GROUP BY authority ORDER BY COUNT(*) DESC "
                f"LIMIT {self.MAX_PROMPT_AUTHORITIES}"
            ).fetchall()
            self._top_authorities = [r[0] for r in rows]

            logger.info(
                f"FilterRegistry: {len(self._top_types)} types, "
                f"{len(self._top_authorities)} authorities loaded from DB"
            )
        finally:
            conn.close()

    def _use_static(self) -> None:
        self._top_types = list(self._STATIC_TYPES)
        self._top_authorities = list(self._STATIC_AUTHORITIES)

    def reload(self) -> None:
        """Force a fresh load from the database."""
        with self._lock:
            self._loaded = False
        self._load()

    # -- public API -----------------------------------------------------

    @property
    def type_values(self) -> Set[str]:
        """The set of accepted type values (same as shown to LLM)."""
        self._load()
        return set(self._top_types)

    @property
    def authority_values(self) -> Set[str]:
        """The set of accepted authority values (same as shown to LLM)."""
        self._load()
        return set(self._top_authorities)

    @property
    def prompt_types(self) -> List[str]:
        """Ordered list of types for the LLM prompt."""
        self._load()
        return list(self._top_types)

    @property
    def prompt_authorities(self) -> List[str]:
        """Ordered list of authorities for the LLM prompt."""
        self._load()
        return list(self._top_authorities)


filter_registry = FilterRegistry()


# ------------------------------------------------------------------
# Rewriter output
# ------------------------------------------------------------------

class RewrittenQuery(BaseModel):
    """A single rewritten query produced by the Rewriter module."""
    text: str = Field(..., max_length=1000, description="Rewritten query text")
    filters: List[SearchFilter] = Field(default_factory=list)
    sorts: List[SearchSort] = Field(default_factory=list)
    facet_type: str = Field("", description="Facet label (e.g. 'temporal', 'authority', 'general')")


# ------------------------------------------------------------------
# Evaluator output
# ------------------------------------------------------------------

class EvaluatedDocument(BaseModel):
    """A document scored by the Evaluator (cross-encoder)."""
    document: Dict[str, Any] = Field(..., description="Original document dict from Searcher")
    relevance_score: float = Field(..., ge=0, le=100, description="Cross-encoder score (0-100)")
    query_text: str = Field("", description="Query the document was evaluated against")


# ------------------------------------------------------------------
# Searcher output
# ------------------------------------------------------------------

class SearchResults(BaseModel):
    """Aggregated search results across all rewritten queries."""
    documents: List[Dict[str, Any]] = Field(default_factory=list)
    results_per_query: Dict[str, int] = Field(
        default_factory=dict,
        description="Map of query text -> number of results returned",
    )
    total_before_dedup: int = 0
    total_after_dedup: int = 0


# ------------------------------------------------------------------
# Pipeline debug trace
# ------------------------------------------------------------------

class StageTimings(BaseModel):
    """Millisecond timings for each pipeline stage."""
    rewriter_ms: int = 0
    searcher_ms: int = 0
    evaluator_ms: int = 0
    generator_ms: int = 0
    total_ms: int = 0


class PipelineTrace(BaseModel):
    """Complete debug trace of a single RAG pipeline execution.

    Returned to the caller when ``debug=True``.  Designed to be
    JSON-serialisable so the web UI can render it directly.
    """
    original_query: str = ""
    rewritten_queries: List[RewrittenQuery] = Field(default_factory=list)

    search_results_per_query: Dict[str, int] = Field(default_factory=dict)
    total_documents_found: int = 0
    documents_after_dedup: int = 0

    evaluation_scores: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="[{regulation_id, score, accepted}]",
    )
    documents_accepted: int = 0
    documents_discarded: int = 0
    evaluation_threshold: float = 0

    generator_model: str = ""
    generator_grounded_only: bool = True
    generator_context_length: int = 0
    generator_documents: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Documents sent to the generator with the text the LLM actually sees",
    )

    timings: StageTimings = Field(default_factory=StageTimings)
    errors: List[str] = Field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump(mode="json")
